/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MerchantService } from "../merchant.service";
import { MerchantCreateInput } from "./MerchantCreateInput";
import { Merchant } from "./Merchant";
import { MerchantFindManyArgs } from "./MerchantFindManyArgs";
import { MerchantWhereUniqueInput } from "./MerchantWhereUniqueInput";
import { MerchantUpdateInput } from "./MerchantUpdateInput";
import { MerchantIdTrackingFindManyArgs } from "../../merchantIdTracking/base/MerchantIdTrackingFindManyArgs";
import { MerchantIdTracking } from "../../merchantIdTracking/base/MerchantIdTracking";
import { MerchantIdTrackingWhereUniqueInput } from "../../merchantIdTracking/base/MerchantIdTrackingWhereUniqueInput";
import { ProductVariantTrackingFindManyArgs } from "../../productVariantTracking/base/ProductVariantTrackingFindManyArgs";
import { ProductVariantTracking } from "../../productVariantTracking/base/ProductVariantTracking";
import { ProductVariantTrackingWhereUniqueInput } from "../../productVariantTracking/base/ProductVariantTrackingWhereUniqueInput";

export class MerchantControllerBase {
  constructor(protected readonly service: MerchantService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Merchant })
  async createMerchant(
    @common.Body() data: MerchantCreateInput
  ): Promise<Merchant> {
    return await this.service.createMerchant({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Merchant] })
  @ApiNestedQuery(MerchantFindManyArgs)
  async merchants(@common.Req() request: Request): Promise<Merchant[]> {
    const args = plainToClass(MerchantFindManyArgs, request.query);
    return this.service.merchants({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Merchant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async merchant(
    @common.Param() params: MerchantWhereUniqueInput
  ): Promise<Merchant | null> {
    const result = await this.service.merchant({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Merchant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMerchant(
    @common.Param() params: MerchantWhereUniqueInput,
    @common.Body() data: MerchantUpdateInput
  ): Promise<Merchant | null> {
    try {
      return await this.service.updateMerchant({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Merchant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMerchant(
    @common.Param() params: MerchantWhereUniqueInput
  ): Promise<Merchant | null> {
    try {
      return await this.service.deleteMerchant({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/merchantIdTrackings")
  @ApiNestedQuery(MerchantIdTrackingFindManyArgs)
  async findMerchantIdTrackings(
    @common.Req() request: Request,
    @common.Param() params: MerchantWhereUniqueInput
  ): Promise<MerchantIdTracking[]> {
    const query = plainToClass(MerchantIdTrackingFindManyArgs, request.query);
    const results = await this.service.findMerchantIdTrackings(params.id, {
      ...query,
      select: {
        createdAt: true,
        expectedArrivals: true,
        id: true,

        merchant: {
          select: {
            id: true,
          },
        },

        noShowPurchases: true,
        product: true,
        refusedPurchases: true,
        successfulPurchases: true,
        totalPurchases: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/merchantIdTrackings")
  async connectMerchantIdTrackings(
    @common.Param() params: MerchantWhereUniqueInput,
    @common.Body() body: MerchantIdTrackingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      merchantIdTrackings: {
        connect: body,
      },
    };
    await this.service.updateMerchant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/merchantIdTrackings")
  async updateMerchantIdTrackings(
    @common.Param() params: MerchantWhereUniqueInput,
    @common.Body() body: MerchantIdTrackingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      merchantIdTrackings: {
        set: body,
      },
    };
    await this.service.updateMerchant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/merchantIdTrackings")
  async disconnectMerchantIdTrackings(
    @common.Param() params: MerchantWhereUniqueInput,
    @common.Body() body: MerchantIdTrackingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      merchantIdTrackings: {
        disconnect: body,
      },
    };
    await this.service.updateMerchant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/productVariantTrackings")
  @ApiNestedQuery(ProductVariantTrackingFindManyArgs)
  async findProductVariantTrackings(
    @common.Req() request: Request,
    @common.Param() params: MerchantWhereUniqueInput
  ): Promise<ProductVariantTracking[]> {
    const query = plainToClass(
      ProductVariantTrackingFindManyArgs,
      request.query
    );
    const results = await this.service.findProductVariantTrackings(params.id, {
      ...query,
      select: {
        color: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        customerConversionSuccessRate: true,
        customerRefusalSuccessRate: true,
        grade: true,
        id: true,

        merchant: {
          select: {
            id: true,
          },
        },

        merchantStarsAtTime: true,
        merchantSuccessRate: true,
        model: true,
        price: true,
        priceAtTime: true,
        product: true,
        size: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/productVariantTrackings")
  async connectProductVariantTrackings(
    @common.Param() params: MerchantWhereUniqueInput,
    @common.Body() body: ProductVariantTrackingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productVariantTrackings: {
        connect: body,
      },
    };
    await this.service.updateMerchant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/productVariantTrackings")
  async updateProductVariantTrackings(
    @common.Param() params: MerchantWhereUniqueInput,
    @common.Body() body: ProductVariantTrackingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productVariantTrackings: {
        set: body,
      },
    };
    await this.service.updateMerchant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/productVariantTrackings")
  async disconnectProductVariantTrackings(
    @common.Param() params: MerchantWhereUniqueInput,
    @common.Body() body: ProductVariantTrackingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productVariantTrackings: {
        disconnect: body,
      },
    };
    await this.service.updateMerchant({
      where: params,
      data,
      select: { id: true },
    });
  }
}
