/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { OrderNotification } from "./OrderNotification";
import { OrderNotificationCountArgs } from "./OrderNotificationCountArgs";
import { OrderNotificationFindManyArgs } from "./OrderNotificationFindManyArgs";
import { OrderNotificationFindUniqueArgs } from "./OrderNotificationFindUniqueArgs";
import { DeleteOrderNotificationArgs } from "./DeleteOrderNotificationArgs";
import { OrderNotificationService } from "../orderNotification.service";
@graphql.Resolver(() => OrderNotification)
export class OrderNotificationResolverBase {
  constructor(protected readonly service: OrderNotificationService) {}

  async _orderNotificationsMeta(
    @graphql.Args() args: OrderNotificationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [OrderNotification])
  async orderNotifications(
    @graphql.Args() args: OrderNotificationFindManyArgs
  ): Promise<OrderNotification[]> {
    return this.service.orderNotifications(args);
  }

  @graphql.Query(() => OrderNotification, { nullable: true })
  async orderNotification(
    @graphql.Args() args: OrderNotificationFindUniqueArgs
  ): Promise<OrderNotification | null> {
    const result = await this.service.orderNotification(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OrderNotification)
  async deleteOrderNotification(
    @graphql.Args() args: DeleteOrderNotificationArgs
  ): Promise<OrderNotification | null> {
    try {
      return await this.service.deleteOrderNotification(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
