/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SalesReport } from "./SalesReport";
import { SalesReportCountArgs } from "./SalesReportCountArgs";
import { SalesReportFindManyArgs } from "./SalesReportFindManyArgs";
import { SalesReportFindUniqueArgs } from "./SalesReportFindUniqueArgs";
import { DeleteSalesReportArgs } from "./DeleteSalesReportArgs";
import { SalesReportService } from "../salesReport.service";
@graphql.Resolver(() => SalesReport)
export class SalesReportResolverBase {
  constructor(protected readonly service: SalesReportService) {}

  async _salesReportsMeta(
    @graphql.Args() args: SalesReportCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SalesReport])
  async salesReports(
    @graphql.Args() args: SalesReportFindManyArgs
  ): Promise<SalesReport[]> {
    return this.service.salesReports(args);
  }

  @graphql.Query(() => SalesReport, { nullable: true })
  async salesReport(
    @graphql.Args() args: SalesReportFindUniqueArgs
  ): Promise<SalesReport | null> {
    const result = await this.service.salesReport(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SalesReport)
  async deleteSalesReport(
    @graphql.Args() args: DeleteSalesReportArgs
  ): Promise<SalesReport | null> {
    try {
      return await this.service.deleteSalesReport(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
