/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SalesReportService } from "../salesReport.service";
import { SalesReportCreateInput } from "./SalesReportCreateInput";
import { SalesReport } from "./SalesReport";
import { SalesReportFindManyArgs } from "./SalesReportFindManyArgs";
import { SalesReportWhereUniqueInput } from "./SalesReportWhereUniqueInput";
import { SalesReportUpdateInput } from "./SalesReportUpdateInput";

export class SalesReportControllerBase {
  constructor(protected readonly service: SalesReportService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SalesReport })
  async createSalesReport(
    @common.Body() data: SalesReportCreateInput
  ): Promise<SalesReport> {
    return await this.service.createSalesReport({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SalesReport] })
  @ApiNestedQuery(SalesReportFindManyArgs)
  async salesReports(@common.Req() request: Request): Promise<SalesReport[]> {
    const args = plainToClass(SalesReportFindManyArgs, request.query);
    return this.service.salesReports({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SalesReport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async salesReport(
    @common.Param() params: SalesReportWhereUniqueInput
  ): Promise<SalesReport | null> {
    const result = await this.service.salesReport({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SalesReport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSalesReport(
    @common.Param() params: SalesReportWhereUniqueInput,
    @common.Body() data: SalesReportUpdateInput
  ): Promise<SalesReport | null> {
    try {
      return await this.service.updateSalesReport({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SalesReport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSalesReport(
    @common.Param() params: SalesReportWhereUniqueInput
  ): Promise<SalesReport | null> {
    try {
      return await this.service.deleteSalesReport({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
