/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Postage } from "./Postage";
import { PostageCountArgs } from "./PostageCountArgs";
import { PostageFindManyArgs } from "./PostageFindManyArgs";
import { PostageFindUniqueArgs } from "./PostageFindUniqueArgs";
import { DeletePostageArgs } from "./DeletePostageArgs";
import { PostageService } from "../postage.service";
@graphql.Resolver(() => Postage)
export class PostageResolverBase {
  constructor(protected readonly service: PostageService) {}

  async _postagesMeta(
    @graphql.Args() args: PostageCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Postage])
  async postages(
    @graphql.Args() args: PostageFindManyArgs
  ): Promise<Postage[]> {
    return this.service.postages(args);
  }

  @graphql.Query(() => Postage, { nullable: true })
  async postage(
    @graphql.Args() args: PostageFindUniqueArgs
  ): Promise<Postage | null> {
    const result = await this.service.postage(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Postage)
  async deletePostage(
    @graphql.Args() args: DeletePostageArgs
  ): Promise<Postage | null> {
    try {
      return await this.service.deletePostage(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
